In [0]:
import numpy as np


jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec = 1,2,3,4,5,6,7,8,9,10,11,12
sun,mon,tue,wed,thu,fri,sat =1,2,3,4,5,6,7






X=np.array([ 8, 8, 8, 8, 7, 7, 7, 6, 6, 6, 6, 5, 8, 6, 6, 6, 5, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 4, 4, 4, 4, 4, 4, 5, 5, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 5, 5, 5, 9, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6, 8, 8, 8, 8, 4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 4, 4, 4, 3, 3, 3, 3, 9, 1, 2, 1, 8, 1, 2, 6, 5, 8, 2, 8, 6, 9, 3, 5, 1, 7, 2, 2, 2, 7, 7, 6, 6, 8, 8, 6, 6, 6, 6, 8, 5, 8, 7, 4, 1, 1, 6, 2, 2, 8, 1, 8, 5, 7, 8, 2, 8, 1, 6, 7, 6, 2, 2, 4, 2, 2, 6, 4, 3, 2, 1, 6, 7, 8, 5, 4, 2, 7, 6, 8, 4, 7, 7, 7, 4, 4, 4, 1, 4, 6, 8, 3, 4, 2, 7, 4, 7, 8, 4, 8, 4, 1, 6, 9, 4, 8, 2, 1, 6, 7, 6, 4, 2, 7, 2, 3, 5, 2, 8, 3, 8, 8, 6, 7, 6, 2, 8, 4, 3, 7, 2, 3, 2, 6, 4, 4, 6, 2, 3, 4, 2, 8, 2, 4, 8, 4, 4, 3, 4, 4, 4, 6, 6, 3, 5, 2, 7, 7, 7, 7, 2, 9, 4, 7, 8, 7, 6, 8, 8, 6, 6, 6, 3, 3, 6, 1, 7, 3, 2, 2, 7, 6, 2, 6, 4, 3, 4, 4, 6, 5, 6, 1, 6, 3, 6, 1, 5, 6, 6, 4, 3, 7, 4, 1, 2, 4, 7, 6, 8, 2, 2, 8, 6, 8, 6, 2, 1, 5, 3, 5, 5, 4, 7, 7, 7, 4, 4, 6, 6, 1, 6, 4, 7, 4, 6, 6, 4, 4, 6, 4, 7, 3, 4, 5, 6, 6, 8, 2, 6, 4, 5, 8, 8, 9, 8, 2, 3, 5, 6, 7, 7, 8, 1, 2, 6, 4, 4, 5, 1, 9, 9, 3, 9, 8, 2, 2, 6, 4, 4, 1, 6, 7, 9, 7, 5, 8, 6, 6, 2, 2, 8, 2, 8, 1, 8, 2, 8, 2, 1, 3, 7, 1, 8, 2, 1, 2, 8, 8, 2, 1, 5, 8, 6, 1, 2, 5, 6, 3, 7, 7, 4, 1, 7, 4, 3, 3, 2, 1, 8, 7, 2, 8, 1, 6, 6, 2, 6, 3, 6, 6, 5, 4, 8, 9, 4, 2, 4, 4, 7, 7, 9, 4, 3, 8, 2, 2, 5, 5, 4, 4, 4, 4, 1, 1, 6, 6, 4, 3, 6, 7, 8, 7, 4, 2, 4, 1, 1, 2, 1, 5, 6, 8, 4, 2, 7, 1, 6]).reshape(512,1)

X_test=np.array([7, 7, 7, 8, 8]).reshape(5,1)


Y=np.array([ 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 5, 4, 4, 4, 9, 9, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 9, 4, 5, 2, 6, 2, 5, 5, 4, 3, 2, 6, 5, 9, 4, 4, 5, 4, 4, 2, 4, 4, 4, 4, 3, 6, 5, 5, 5, 5, 5, 6, 4, 6, 4, 4, 4, 4, 5, 5, 5, 6, 3, 6, 4, 4, 6, 5, 6, 5, 4, 4, 5, 5, 2, 5, 2, 5, 5, 5, 4, 4, 5, 5, 4, 6, 6, 5, 2, 5, 5, 3, 4, 4, 4, 3, 4, 4, 4, 3, 5, 5, 6, 4, 3, 2, 4, 4, 5, 6, 6, 6, 4, 5, 4, 4, 5, 6, 2, 2, 5, 5, 3, 4, 4, 4, 4, 4, 4, 4, 6, 4, 5, 5, 5, 4, 3, 5, 6, 3, 4, 4, 4, 4, 4, 3, 4, 4, 5, 2, 4, 4, 2, 6, 5, 6, 6, 6, 4, 4, 4, 4, 6, 5, 3, 4, 4, 5, 6, 4, 4, 4, 5, 4, 5, 6, 6, 5, 4, 6, 6, 5, 5, 5, 6, 6, 5, 4, 4, 4, 4, 4, 4, 3, 4, 5, 4, 4, 5, 4, 5, 4, 3, 4, 5, 5, 5, 4, 4, 5, 5, 3, 3, 4, 4, 4, 3, 3, 4, 3, 6, 4, 5, 6, 3, 6, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 5, 3, 4, 3, 5, 5, 5, 5, 5, 5, 4, 4, 5, 4, 5, 5, 6, 2, 5, 5, 4, 6, 6, 6, 4, 4, 4, 5, 4, 4, 4, 6, 3, 4, 5, 5, 3, 6, 2, 5, 5, 4, 9, 6, 4, 2, 5, 5, 3, 4, 3, 4, 4, 5, 4, 6, 3, 5, 4, 5, 8, 4, 6, 3, 6, 2, 6, 4, 3, 4, 4, 3, 6, 4, 4, 5, 6, 6, 5, 3, 4, 6, 5, 2, 5, 5, 5, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 6, 4, 5, 6, 4, 5, 4, 2, 5, 4, 5, 3, 4, 3, 3, 4, 3, 5, 3, 3, 4, 4, 9, 3, 4, 6, 5, 4, 4, 4, 4, 4, 4, 4, 3, 3, 6, 6, 5, 4, 5, 5, 6, 5, 4, 4, 3, 2, 2, 4, 2, 4, 5, 6, 3, 4, 4, 4, 3]).reshape(512,1)

Y_test=np.array([ 5, 4, 4, 6, 6]).reshape(5,1)
wind=np.array([ 5.4, 3.1, 2.2, 5.4, 4, 7.2, 4, 6.7, 2.2, 4.5, 5.4, 5.4, 4.9, 4, 4.5, 2.7, 2.7, 4.5, 5.8, 5.8, 5.4, 5.8, 1.3, 2.7, 3.6, 3.6, 7.6, 1.8, 3.6, 2.7, 4.5, 4.5, 5.4, 4, 2.7, 3.1, 6.7, 5.4, 2.7, 4.9, 4, 3.6, 3.1, 1.8, 5.8, 1.3, 2.2, 4.9, 4.9, 3.6, 2.2, 4.9, 2.7, 5.4, 0.9, 5.8, 6.3, 4.9, 2.7, 3.1, 4.5, 4.5, 5.4, 6.3, 4.5, 7.6, 3.6, 6.3, 4.5, 1.3, 3.1, 3.1, 3.1, 2.7, 6.7, 6.3, 2.2, 4.5, 0.9, 3.6, 0.9, 2.2, 2.2, 3.6, 4.9, 5.8, 5.4, 6.3, 4.9, 2.7, 1.3, 1.8, 5.4, 4.5, 5.4, 5.4, 5.4, 4, 4.5, 3.1, 6.3, 3.1, 3.1, 3.1, 5.4, 5.8, 4.5, 3.6, 2.7, 7.6, 6.3, 6.3, 4.9, 4, 3.1, 2.2, 5.4, 5.4, 3.1, 5.4, 5.4, 2.2, 3.1, 3.6, 0.9, 2.7, 3.1, 4.9, 3.1, 2.7, 5.8, 1.3, 3.1, 2.7, 2.2, 1.8, 4.5, 8.9, 5.4, 5.4, 4, 5.4, 3.6, 6.7, 4.5, 5.4, 2.2, 1.8, 4.9, 2.7, 1.3, 2.2, 3.6, 4, 5.8, 3.1, 4, 8.5, 1.8, 2.2, 4.5, 0.9, 4.5, 9.4, 2.2, 1.8, 4, 5.4, 2.2, 1.8, 4.9, 5.8, 2.7, 2.2, 5.4, 6.7, 4, 2.2, 4.5, 4.9, 3.1, 5.8, 2.2, 0.9, 4, 4, 2.7, 4.5, 4, 4.5, 5.4, 5.8, 0.9, 6.3, 3.6, 2.2, 3.6, 2.2, 2.7, 4, 1.8, 7.2, 2.2, 6.3, 4.9, 3.1, 5.8, 4.9, 5.8, 4.9, 4.9, 1.3, 6.3, 1.3, 3.1, 3.1, 3.6, 5.8, 3.6, 4.5, 4.9, 4, 4.5, 3.1, 4, 4.5, 3.1, 2.7, 3.1, 3.1, 5.8, 1.8, 2.2, 4, 1.8, 2.7, 3.1, 4, 7.6, 7.6, 6.3, 5.4, 2.2, 2.7, 0.4, 3.1, 3.1, 3.6, 2.7, 3.1, 4, 2.2, 2.7, 0.9, 1.8, 4, 7.6, 3.1, 3.6, 3.1, 7.6, 4, 3.1, 3.1, 2.7, 3.1, 4.5, 4, 8.5, 8, 4.9, 8.5, 8.5, 8.5, 8.5, 4.9, 8.5, 4, 3.1, 8, 6.3, 7.6, 2.7, 1.8, 1.8, 1.8, 0.9, 1.3, 5.4, 3.6, 1.3, 1.8, 2.2, 4.9, 2.7, 4.9, 5.4, 4.5, 4.5, 4.9, 2.2, 5.4, 3.6, 1.8, 2.2, 2.7, 1.8, 6.3, 4.9, 1.8, 2.7, 5.8, 4.9, 2.2, 6.3, 7.2, 4, 4, 2.7, 1.8, 3.1, 3.1, 2.2, 1.8, 4, 3.1, 4.5, 2.2, 3.1, 5.4, 1.8, 2.2, 2.2, 2.2, 1.8, 2.2, 2.2, 1.8, 4.5, 4.9, 3.1, 2.2, 3.6, 4.5, 3.6, 3.6, 6.3, 3.6, 2.7, 2.2, 4.9, 4.9, 3.6, 2.7, 2.2, 2.2, 4, 3.1, 2.2, 2.7, 3.1, 5.4, 3.6, 4.9, 7.6, 7.6, 4, 0.9, 2.7, 4, 4.9, 2.2, 2.2, 5.8, 0.9, 7.2, 2.7, 1.8, 2.7, 4.5, 2.2, 5.4, 5.4, 3.1, 3.1, 6.3, 2.7, 4, 7.6, 1.8, 1.8, 4.9, 3.6, 3.1, 4.5, 4.5, 4, 4, 3.6, 2.2, 2.2, 4.9, 4, 3.1, 5.4, 2.7, 9.4, 4.5, 3.6, 4, 4.9, 3.1, 5.8, 5.4, 4, 4.5, 4.5, 3.6, 4, 3.6, 2.2, 2.2, 2.2, 5.8, 4, 3.6, 4, 6.7, 4.9, 3.6, 1.8, 1.3, 2.7, 4, 2.2, 3.6, 1.8, 3.1, 8, 3.6, 4.5, 2.2, 8, 4, 4.9, 5.4, 4.9, 4, 3.1, 3.1, 2.7, 2.7, 4, 4.9, 8, 4.9, 4.9, 7.6, 6.3, 5.4, 0.9, 5.8, 5.4, 3.6, 9.4, 5.8, 4, 4, 3.1, 2.7, 9.4, 1.3, 4, 4.5, 4.9, 4.5, 4.9, 5.8, 5.4, 4, 3.6, 6.3, 3.6, 7.6, 1.3, 4, 4.5, 2.2, 4.5, 4.9, 2.2, 3.1, 2.2, 2.7, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 1.8, 8.5, 3.6, 3.6, 7.6, 5.4, 2.7, 2.7, 5.8, 6.7, 4, 4.5]).reshape(512,1)

wind_test=np.array([6.7, 0.9, 1.3, 4, 1.8 ]).reshape(5,1)            
             

In [0]:
c1=np.array([1 for i in range(512)]).reshape(512,1)

c2=np.array([1 for i in range(5)]).reshape(5,1)

x_train=np.concatenate([c1,X,Y],axis=1) # used for training

x_test=np.concatenate([c2,X_test,Y_test],axis=1) #used for testing

print(x_train)
print(x_test)

[[1 8 6]
 [1 8 6]
 [1 8 6]
 ...
 [1 7 4]
 [1 1 4]
 [1 6 3]]
[[1 7 5]
 [1 7 4]
 [1 7 4]
 [1 8 6]
 [1 8 6]]


In [0]:
from numpy.linalg import lstsq
THETA_LS=lstsq(x_train,wind)[0]
print(THETA_LS)

[[ 4.14257455]
 [ 0.04041585]
 [-0.07036699]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,wind)



y_predict=model.predict(x_test)
print(np.shape(y_predict))
print(y_predict)

(5, 1)
[[4.07365055]
 [4.14401755]
 [4.14401755]
 [4.04369941]
 [4.04369941]]


In [0]:
model.score(x_test,wind_test)

-0.30471099193016293